# DO NOT EDIT THIS FILE!
#
# Python module HelloWorld generated by omniidl

import omniORB
omniORB.updateModule("HelloWorld")

# ** 1. Stub files contributing to this module
import atvcorba_idl

# ** 2. Sub-modules

# ** 3. End
